import {normalize} from '../utils'

const DEFAULT_BOTTOM_SIZE = normalize(20)
const DEFAULT_BOTTOM_TABBAR = normalize(50)
const MAIN_HEADER_MAX_SIZE = normalize(200)
const MAIN_HEADER_MIN_SIZE = normalize(100)

const MAIN_HEADER_TEXT_MIN_SIZE = normalize(22)
const MAIN_HEADER_TEXT_MAX_SIZE = normalize(34)

const MAIN_HEADER_TITLE_MIN_SIZE = normalize(16)
const MAIN_HEADER_TITLE_MAX_SIZE = normalize(24)

export {
  DEFAULT_BOTTOM_SIZE,
  DEFAULT_BOTTOM_TABBAR,
  MAIN_HEADER_MAX_SIZE,
  MAIN_HEADER_MIN_SIZE,
  MAIN_HEADER_TEXT_MIN_SIZE,
  MAIN_HEADER_TEXT_MAX_SIZE,
  MAIN_HEADER_TITLE_MIN_SIZE,
  MAIN_HEADER_TITLE_MAX_SIZE,
}
